"""DetailWidgetsModel, strict to a type checker, all-optional at runtime.

A type checker reads the strict model, so every field carries the type and
the requiredness the schema recorded. At runtime the all-optional copy is imported
instead, so a response that has drifted still parses and a field the data is
missing is None despite what its type hint says.
"""

from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import DetailWidgetsModel as OptionalModel
from .strict_models import DetailWidgetsModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Action,
        Action1,
        Action2,
        Actions,
        Availability,
        Banner,
        CardOption,
        ComponentPayload,
        ComponentPayload1,
        ComponentPayload2,
        ComponentPayload3,
        Components,
        Components1,
        Contributors,
        Detail,
        DetailWidgetsModel,
        DvMessage,
        EnhancedSubtitle,
        Episode,
        EpisodeList,
        EpisodePage,
        ExpandingCard,
        Features,
        FocusMessage,
        Genre,
        Header,
        Images,
        MaturityRating,
        Messages,
        Metadata,
        Metadata1,
        PageContext,
        PaginationItem,
        Payload,
        Payload1,
        Payload2,
        Presentation,
        Presentation2,
        PrimaryAction,
        PurchaseData,
        Self,
        SortItem,
        Tags,
        Text,
        TextComponent,
        TextComponent2,
        TextComponentCollection,
        TextListItem,
        Tokens,
        Transaction,
        Transaction1,
        TransactionDetail,
        TransactionDetail1,
        Widgets,
    )
else:
    from .optional_models import (
        Action,
        Action1,
        Action2,
        Actions,
        Availability,
        Banner,
        CardOption,
        ComponentPayload,
        ComponentPayload1,
        ComponentPayload2,
        ComponentPayload3,
        Components,
        Components1,
        Contributors,
        Detail,
        DetailWidgetsModel,
        DvMessage,
        EnhancedSubtitle,
        Episode,
        EpisodeList,
        EpisodePage,
        ExpandingCard,
        Features,
        FocusMessage,
        Genre,
        Header,
        Images,
        MaturityRating,
        Messages,
        Metadata,
        Metadata1,
        PageContext,
        PaginationItem,
        Payload,
        Payload1,
        Payload2,
        Presentation,
        Presentation2,
        PrimaryAction,
        PurchaseData,
        Self,
        SortItem,
        Tags,
        Text,
        TextComponent,
        TextComponent2,
        TextComponentCollection,
        TextListItem,
        Tokens,
        Transaction,
        Transaction1,
        TransactionDetail,
        TransactionDetail1,
        Widgets,
    )

__all__ = [
    "Action",
    "Action1",
    "Action2",
    "Actions",
    "Availability",
    "Banner",
    "CardOption",
    "ComponentPayload",
    "ComponentPayload1",
    "ComponentPayload2",
    "ComponentPayload3",
    "Components",
    "Components1",
    "Contributors",
    "Detail",
    "DetailWidgetsModel",
    "DvMessage",
    "EnhancedSubtitle",
    "Episode",
    "EpisodeList",
    "EpisodePage",
    "ExpandingCard",
    "Features",
    "FocusMessage",
    "Genre",
    "Header",
    "Images",
    "MaturityRating",
    "Messages",
    "Metadata",
    "Metadata1",
    "PageContext",
    "PaginationItem",
    "Payload",
    "Payload1",
    "Payload2",
    "Presentation",
    "Presentation2",
    "PrimaryAction",
    "PurchaseData",
    "Self",
    "SortItem",
    "Tags",
    "Text",
    "TextComponent",
    "TextComponent2",
    "TextComponentCollection",
    "TextListItem",
    "Tokens",
    "Transaction",
    "Transaction1",
    "TransactionDetail",
    "TransactionDetail1",
    "Widgets",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> DetailWidgetsModel:
    """Read a downloaded file into DetailWidgetsModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
